### ISSUE TITLE
babelify required in dependencies?

### ISSUE THREAD

**Issue by jywarren** [canastro/image-filter-threshold#1]
Hi, new-ish to browserify, but when I try to require this library with it, I see these errors:

```
>> Error: Cannot find module 'babelify' from '/home/warren/sites/imageboard/node_modules/image-filter-threshold'
```

Anyways I then tried manually installing `babelify`, but then still got:

```
>> ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "/home/warren/sites/imageboard/node_modules/image-filter-threshold/.babelrc" at 0, attempted to resolve relative to "/home/warren/sites/imageboard/node_modules/image-filter-threshold" while parsing file: /home/warren/sites/imageboard/node_modules/image-filter-threshold/src/index.js
```

Should compiling the lib with browserify need the devDependencies? I thought not? But I could be doing something simple incorrectly.

**Comment by canastro** [comment]
Sorry, I haven't invested much time on this module. I only created it for a dummy project I was working on.

- You were right, I had some babel transformations in my .babelrc file that I shouldn't have (spread and object assign). Removed these.
- `Babelify` is not as a dependency, because someone might want to use this module with webpack. But the babel es2015 transformation should be a dependency. Changed that.
- In this module I'm using `import` instead of `require` and for that reason is required for you to use the es2015 babel transform. In your project add a .babelrc file with the following content: `{ "presets": ["es2015"] }`

I just published version 0.0.9. Try it and tell me what issues you find, I'll be glad to help you out. This is also a good opportunity for me to understand what I haven't thought through. 

PS: Are you thinking on using any of the others image-filter modules? They might suffer from the same issues.

**Comment by jywarren** [comment]
Oh, wow, thank you so much! Yes, I am interested in the other modules -- if you have time to make the changes, it'd be much appreciated; I'd try myself in a PR, but this looks a bit delicate for someone new to the codebase:

https://github.com/canastro/image-filter-threshold/commit/d966f9cc13dbfcc96606e5e2abc9a57f298270f7

Thank you! I'll give it a try in the next few days.

**Comment by canastro** [comment]
I had a bit of free time and I've already applied and publish this changes to all of the modules :)

**Comment by jywarren** [comment]
Hmm, with v0.0.9 i still get:

`>> Error: Cannot find module 'babelify' from '/home/warren/sites/imageboard/node_modules/image-filter-threshold'`

after installing v0.0.9 and running "npm install". I did also try adding the `.babelrc` but got the same result.

**Comment by jywarren** [comment]
Oh wow, so fast! Thank you! I'm sorry it didn't seem to work -- could it be related to my using browserify instead of webpack?

**Comment by jywarren** [comment]
I'm just requiring it with `require('image-filter-threshold')`

**Comment by canastro** [comment]
No no, browserify is what you should use, but you need to babelify your code (make it es2015 compatible).

If you're using a npm script, make it something like this: `"build": "browserify -t babelify entry.js > output.js -d",`.

If you're using gulp it can be something like this: 

```
const browserify = require('browserify');
const babelify = require('babelify');
const source = require('vinyl-source-stream');
const buffer = require('vinyl-buffer');

return browserify('./entry.js', { debug: true })
        .transform(babelify, { sourceMaps: false })
        .bundle()
        .pipe(source('sample.js'))
        .pipe(buffer())
        .pipe(gulp.dest('./dist/scripts/sample'));
```

**Comment by jywarren** [comment]
hmm, but if I'm just requiring this library, should it be required of a
containing codebase to conform to the module's syntax? Isn't babelify to
ensure the containing code needn't? Sorry, I haven't used babelify before,
just learning! Thanks!

**Comment by canastro** [comment]
Yeah, I've never exported a babelify module to other modules that don't use babelify.
I tried to create a bundle file already babelified for you to require, but had some issues. So, for now I just dropped my es6 code to es5.

You can try put your dependency in the package.json like this: `"image-filter-threshold": "git+https://github.com/canastro/image-filter-threshold#prebundle"`, if it works I'll merge the code to master and publish the module.

**Comment by jywarren** [comment]
That worked -- thank you!
